<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.9.2
 * 
 * System quest created in: 2020-06-05 23:04:07
 */

define('BANCO'   , 'SQLITE');
define('HOST'    , '');
define('PORT'    , '');
define('DATABASE', 'banco_local\banco.sqlite3');
define('SCHEMA'  , '');
define('USUARIO' , '');
define('SENHA'   , '');
define('UTF8_DECODE'   , 0); //Decode String APP (UTF-8) to Database ISO-8859-1
?>