<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.9.2
 * 
 * System quest created in: 2020-06-05 23:04:07
 */

define('FORMDIN_VERSION_MIN', '4.9.2');

define('SYSTEM_VERSION' , '0.0.0');
define('SYSTEM_ACRONYM' , 'quest');
define('APLICATIVO'     , SYSTEM_ACRONYM);
define('SYSTEM_NAME'    , 'quest');
//define('SYSTEM_NAME_SUB' , 'Subtítulo do sistema');
//define('SYSTEM_UNIT' , 'Nome unidade que irá aparecer no rodapé');

if (! defined ( 'DS' )) {
    define('DS'   , DIRECTORY_SEPARATOR);
}
?>