-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 15:38:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema form_exemplo
-- -----------------------------------------------------
-- banco de dados de exemplo para utilizar o formDin	
DROP SCHEMA IF EXISTS `form_exemplo` ;

-- -----------------------------------------------------
-- Schema form_exemplo
--
-- banco de dados de exemplo para utilizar o formDin	
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `form_exemplo` DEFAULT CHARACTER SET latin1 ;
USE `form_exemplo` ;

-- -----------------------------------------------------
-- Table `form_exemplo`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `tipo` CHAR(2) NOT NULL COMMENT '\'Valor permitidos PF ou PJ\'',
  `dat_inclusao` DATETIME NOT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`tipo_de_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`tipo_de_tipos` (
  `idtipo_de_tipos` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `sit_ativo` CHAR(1) NULL DEFAULT 'S',
  PRIMARY KEY (`idtipo_de_tipos`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`tipo` (
  `idtipo` INT NOT NULL,
  `idtipo_de_tipos` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `sit_ativo` CHAR(1) NULL,
  PRIMARY KEY (`idtipo`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC),
  INDEX `fk_tipo_tipo_de_tipos_idx` (`idtipo_de_tipos` ASC),
  CONSTRAINT `fk_tipo_tipo_de_tipos`
    FOREIGN KEY (`idtipo_de_tipos`)
    REFERENCES `form_exemplo`.`tipo_de_tipos` (`idtipo_de_tipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`regiao` (
  `cod_regiao` INT NOT NULL,
  `nom_regiao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_regiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`uf` (
  `cod_uf` INT NOT NULL,
  `nom_uf` VARCHAR(45) NOT NULL,
  `sig_uf` VARCHAR(45) NOT NULL COMMENT 'sigla da uf',
  `cod_regiao` INT NOT NULL,
  PRIMARY KEY (`cod_uf`),
  INDEX `fk_uf_regiao1_idx` (`cod_regiao` ASC),
  CONSTRAINT `fk_uf_regiao1`
    FOREIGN KEY (`cod_regiao`)
    REFERENCES `form_exemplo`.`regiao` (`cod_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`municipio` (
  `cod_municipio` INT NOT NULL,
  `cod_uf` INT NOT NULL,
  `nom_municipio` VARCHAR(200) NOT NULL,
  `sit_ativo` VARCHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`cod_municipio`),
  INDEX `fk_municipio_uf1_idx` (`cod_uf` ASC),
  CONSTRAINT `fk_municipio_uf1`
    FOREIGN KEY (`cod_uf`)
    REFERENCES `form_exemplo`.`uf` (`cod_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`autoridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`autoridade` (
  `idautoridade` INT NOT NULL AUTO_INCREMENT,
  `dat_inclusao` DATETIME NOT NULL DEFAULT now(),
  `dat_evento` DATE NOT NULL COMMENT 'Data do evento',
  `ordem` INT NOT NULL COMMENT 'ordem daa autoridades',
  `cargo` VARCHAR(100) NOT NULL COMMENT 'nome do cargo da autoridade',
  `nome_pessoa` VARCHAR(100) NOT NULL COMMENT 'nome da pessoa',
  PRIMARY KEY (`idautoridade`))
ENGINE = InnoDB
COMMENT = 'Tabela idependete de qualquer outra do sistema';


-- -----------------------------------------------------
-- Table `form_exemplo`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`pessoa_fisica` (
  `idpessoa_fisica` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dat_nascimento` DATE NULL,
  `cod_municipio_nascimento` INT NULL,
  `dat_inclusao` DATETIME NOT NULL DEFAULT NOW(),
  `dat_alteracao` DATETIME NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`idpessoa_fisica`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_pessoa_fisica_pessoa1_idx` (`idpessoa` ASC),
  INDEX `fk_pessoa_fisica_municipio1_idx` (`cod_municipio_nascimento` ASC),
  CONSTRAINT `fk_pessoa_fisica_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `form_exemplo`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_fisica_municipio1`
    FOREIGN KEY (`cod_municipio_nascimento`)
    REFERENCES `form_exemplo`.`municipio` (`cod_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`acesso_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`acesso_user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nom_user` VARCHAR(45) NOT NULL,
  `pwd_user` VARCHAR(45) NULL,
  `sit_ativo` VARCHAR(1) NOT NULL DEFAULT 'S',
  `dat_inclusao` DATETIME NOT NULL DEFAULT NOW(),
  `dat_update` DATETIME NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `nom_usuario_UNIQUE` (`nom_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`acesso_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`acesso_perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nom_perfil` VARCHAR(45) NOT NULL,
  `sit_ativo` VARCHAR(1) NOT NULL DEFAULT 'S',
  `dat_inclusao` DATETIME NOT NULL DEFAULT NOW(),
  `dat_update` DATETIME NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`idperfil`),
  UNIQUE INDEX `nom_perfil_UNIQUE` (`nom_perfil` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`acesso_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`acesso_menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `idmenu_pai` INT NULL COMMENT 'id do menu pai, se o pai é null então começa na raiz',
  `nom_menu` VARCHAR(45) NOT NULL COMMENT 'o nome que o usuario irá ver',
  `url` VARCHAR(45) NULL,
  `toolpip` VARCHAR(45) NULL,
  `img_menu` VARCHAR(45) NULL,
  `imgdisabled` VARCHAR(45) NULL,
  `dissabled` TINYINT NULL,
  `hotkey` VARCHAR(45) NULL,
  `separator` VARCHAR(45) NULL,
  PRIMARY KEY (`idmenu`),
  INDEX `fk_acesso_menu_pai_idx` (`idmenu_pai` ASC),
  CONSTRAINT `fk_acesso_menu_pai`
    FOREIGN KEY (`idmenu_pai`)
    REFERENCES `form_exemplo`.`acesso_menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`acesso_perfil_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`acesso_perfil_menu` (
  `idperfilmenu` INT NOT NULL AUTO_INCREMENT,
  `idperfil` INT NOT NULL,
  `idmenu` INT NOT NULL,
  `sit_ativo` VARCHAR(1) NOT NULL DEFAULT 'S',
  `dat_inclusao` DATETIME NOT NULL DEFAULT NOW(),
  `dat_update` DATETIME NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`idperfilmenu`),
  INDEX `fk_acesso_perfil_menu_acesso_perfil1_idx` (`idperfil` ASC),
  INDEX `fk_acesso_perfil_menu_acesso_menu1_idx` (`idmenu` ASC),
  CONSTRAINT `fk_acesso_perfil_menu_acesso_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `form_exemplo`.`acesso_perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acesso_perfil_menu_acesso_menu1`
    FOREIGN KEY (`idmenu`)
    REFERENCES `form_exemplo`.`acesso_menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`acesso_perfil_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`acesso_perfil_user` (
  `idperfiluser` INT NOT NULL AUTO_INCREMENT,
  `idperfil` INT NOT NULL,
  `iduser` INT NOT NULL,
  `sit_ativo` VARCHAR(1) NOT NULL DEFAULT 'S',
  `dat_inclusao` DATETIME NOT NULL DEFAULT NOW(),
  `dat_update` DATETIME NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`idperfiluser`),
  INDEX `fk_acesso_perfil_user_acesso_user1_idx` (`iduser` ASC),
  INDEX `fk_acesso_perfil_user_acesso_perfil1_idx` (`idperfil` ASC),
  CONSTRAINT `fk_acesso_perfil_user_acesso_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `form_exemplo`.`acesso_user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acesso_perfil_user_acesso_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `form_exemplo`.`acesso_perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
