-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 15:00:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema form_exemplo
-- -----------------------------------------------------
-- banco de dados de exemplo para utilizar o formDin	
DROP SCHEMA IF EXISTS `form_exemplo` ;

-- -----------------------------------------------------
-- Schema form_exemplo
--
-- banco de dados de exemplo para utilizar o formDin	
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `form_exemplo` DEFAULT CHARACTER SET utf8 ;
USE `form_exemplo` ;

-- -----------------------------------------------------
-- Table `form_exemplo`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `tipo` CHAR(2) NOT NULL COMMENT '\'Valor permitidos PF ou PJ\'',
  `dat_inclusao` DATETIME NOT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`tipo_de_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`tipo_de_tipos` (
  `idtipo_de_tipos` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `sit_ativo` CHAR(1) NULL DEFAULT 'S',
  PRIMARY KEY (`idtipo_de_tipos`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`tipo` (
  `idtipo` INT NOT NULL,
  `idtipo_de_tipos` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `sit_ativo` CHAR(1) NULL,
  PRIMARY KEY (`idtipo`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC),
  INDEX `fk_tipo_tipo_de_tipos_idx` (`idtipo_de_tipos` ASC),
  CONSTRAINT `fk_tipo_tipo_de_tipos`
    FOREIGN KEY (`idtipo_de_tipos`)
    REFERENCES `form_exemplo`.`tipo_de_tipos` (`idtipo_de_tipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`regiao` (
  `idregiao` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idregiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`estado` (
  `idestado` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idestado` INT NULL,
  `municipiocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `form_exemplo`.`autoridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_exemplo`.`autoridade` (
  `idautoridade` INT NOT NULL AUTO_INCREMENT,
  `dat_inclusao` DATETIME NOT NULL DEFAULT now(),
  `dat_inicio` DATETIME NOT NULL COMMENT 'primeiro dia que pessoa virou autoridade',
  `dat_fim` DATETIME NULL COMMENT 'ultima da pessoa no cargo',
  `cargo` VARCHAR(100) NOT NULL COMMENT 'nome do cargo da autoridade',
  `nome_pessoa` VARCHAR(100) NOT NULL COMMENT 'nome da pessoa',
  `ordem` INT NOT NULL COMMENT 'ordem daa autoridades',
  PRIMARY KEY (`idautoridade`))
ENGINE = InnoDB
COMMENT = 'Tabela idependete de qualquer outra do sistema';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
