<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.9.0-alpha
 * FormDin Version: 4.7.5
 * 
 * System appev2 created in: 2019-09-10 09:04:14
 */
if (! defined ( 'DS' )) {
	define ( 'DS', DIRECTORY_SEPARATOR );
}

// sqlite
define('BANCO', 'SQLITE');
define('DATABASE', __DIR__.DS.'..'.DS.'local_database'.DS.'bdApoio.s3db');
define('UTF8_DECODE', 0);
?>