<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.9.0-alpha
 * FormDin Version: 4.7.5
 * 
 * System appev2 created in: 2019-09-10 09:04:14
 */

define('BANCO'   , 'MYSQL');
define('HOST'    , 'localhost');
define('PORT'    , '3306');
define('DATABASE', 'form_exemplo');
define('SCHEMA'  , '');
define('USUARIO' , 'form_exemplo');
define('SENHA'   , '123456');
define('UTF8_DECODE'   , 0);
?>