<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-21 23:29:28
 */

define('SYSTEM_NAME'    , 'ap2v');
define('SYSTEM_ACRONYM' , 'ap2v');
define('SYSTEM_VERSION' , '0.0.0');
define('APLICATIVO'     , SYSTEM_ACRONYM);
define('DS'   , DIRECTORY_SEPARATOR);
?>