<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-21 23:30:53
 */

$menu = new TMenuDhtmlx();
$menu->add('1', null, 'Menu', null, null, 'menu-alt-512.png');
$menu->add('1.1',1,'marca','modulos/marca.php');
$menu->add('1.2',1,'pedido','modulos/pedido.php');
$menu->add('1.3',1,'pedido_item','modulos/pedido_item.php');
$menu->add('1.4',1,'produto','modulos/produto.php');

$menu->add('2', null, 'Pessoas', null, null);
$menu->add('2.1',2,'pessoa','modulos/pessoa.php');
$menu->add('2.2',2,'pessoa_fisica','modulos/pessoa_fisica.php');
$menu->add('2.3',2,'pessoa_juridica','modulos/pessoa_juridica.php');

$menu->add('3', null, 'Autoridades', null, null);
$menu->add('3.1', 3, 'Cadastro Autoridades', 'modulos/autoridade.php', null);

$menu->add('8', null, 'Tabelas de Apoio', null, null, 'table16.gif');
$menu->add('8.1', 8,'Região', 'modulos/regiao.php', null, null, null, false, null);
$menu->add('8.2', 8,'UF','modulos/uf.php');
$menu->add('8.3', 8,'Município','modulos/municipio.php');
$menu->add('8.4', 8,'Meta Tipo','modulos/meta_tipo.php');
$menu->add('8.5', 8,'Tipo','modulos/tipo.php');

$menu->add('9', null, 'Acesso', null, null, 'icon-key-yellow.png');
$menu->add('9.1', 9, 'Usuários', 'modulos/acesso_user.php', null, 'user916.gif');
$menu->add('9.2', 9, 'Pefil de Acesso', 'modulos/acesso_perfil.php', null, 'icon_mask.png');
$menu->add('9.3', 9, 'Menu', 'modulos/acesso_menu.php', null, 'icon-menu.png');
$menu->add('9.4', 9, 'Relacionar Perfil com Menu','modulos/acesso_perfil_menu.php');
$menu->add('9.5', 9, 'Relacionar Perfil com Usuário','modulos/acesso_perfil_user.php');


$menu->add('10',null,'Config Ambiente',null,null,'setting-gear-512.png');
$menu->add('10.1',10,'Ambiente Resumido','modulos/sys_environment_summary.php',null,'information-circle.jpg');
$menu->add('10.2',10,'PHPInfo','modulos/sys_environment.php',null,'php_logo.png');
$menu->add('10.4',10,'Gerador VO/DAO','../base/includes/gerador_vo_dao.php');
$menu->add('10.5',10,'Gerador Form VO/DAO','../base/includes/gerador_form_vo_dao.php',null,'smiley-1-512.png');

$menu->add('11', null, 'Sobre', 'modulos/sys_about.php', null, 'information-circle.jpg');

$menu->getXml();
?>