<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-21 23:30:54
 */

class Acesso_user {


	public function __construct(){
	}
	//--------------------------------------------------------------------------------
	public static function selectById( $id ){
		$result = Acesso_userDAO::selectById( $id );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectCount( $where=null ){
		$result = Acesso_userDAO::selectCount( $where );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectAllPagination( $orderBy=null, $where=null, $page=null,  $rowsPerPage= null){
		$result = Acesso_userDAO::selectAllPagination( $orderBy, $where, $page,  $rowsPerPage );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectAll( $orderBy=null, $where=null ){
		$result = Acesso_userDAO::selectAll( $orderBy, $where );
		return $result;
	}
	//--------------------------------------------------------------------------------	
	public static function login( $login_user, $pwd_user )	{
		$user = Acesso_userDAO::selectByLogin($login_user);
        if (password_verify($pwd_user, $user['PWD_USER'][0])) {
            $_SESSION[APLICATIVO]['IDUSER'] = $user['IDUSER'][0];
            $_SESSION[APLICATIVO]['LOGIN']  = $user['LOGIN_USER'][0];
            $msg = 1;
        }else{
            $msg = 'Login Invalido !';
        }
        return $msg;
    }	
	//--------------------------------------------------------------------------------
	public static function save( Acesso_userVO $objVo ){
		$result = null;
		if( $objVo->getIduser() ) {
			$result = Acesso_userDAO::update( $objVo );
		} else {
			$result = Acesso_userDAO::insert( $objVo );
		}
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function delete( $id ){
		$result = Acesso_userDAO::delete( $id );
		return $result;
	}

}
?>