<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-21 23:30:54
 */

class Acesso {


	public function __construct(){
    }    
	//--------------------------------------------------------------------------------	
	public static function login( $login_user, $pwd_user )	{
		$user = Acesso_userDAO::selectByLogin($login_user);
        if (password_verify($pwd_user, $user['PWD_USER'][0])) {
            $_SESSION[APLICATIVO]['IDUSER'] = $user['IDUSER'][0];
            $_SESSION[APLICATIVO]['LOGIN']  = $user['LOGIN_USER'][0];
            $msg = 1;
        }else{
            $msg = 'Login Invalido !';
        }
        return $msg;
    }    
	//--------------------------------------------------------------------------------
	public static function getAcessoUserMenuByLogin()	{
	    $login = $_SESSION[APLICATIVO]['LOGIN'];
        $userMenu = Acesso_menuDAO::selectMenuByLogin($login);
        return $userMenu;
    }
	public static function changePassword($login_user, $pwd_user_old, $pwd_user_new)	{
		$user = Acesso_userDAO::selectByLogin($login_user);
        if (password_verify($pwd_user, $user['PWD_USER'][0])) {
            $_SESSION[APLICATIVO]['IDUSER'] = $user['IDUSER'][0];
            $_SESSION[APLICATIVO]['LOGIN']  = $user['LOGIN_USER'][0];
            $msg = 1;
        }else{
            throw new DomainException('A senha atual não está valida');
        }
        return $msg;
    }    
}
?>