<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0-alpha
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-20 23:14:14
 */

if ( !function_exists( 'ap2v_autoload') ) {
	function ap2v_autoload( $class_name )	{
		require_once $class_name . '.class.php';
	}
spl_autoload_register('ap2v_autoload');
}