<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0-alpha
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-20 23:02:03
 */

class Tipo_de_tipos {


	public function __construct(){
	}
	//--------------------------------------------------------------------------------
	public static function selectById( $id ){
		$result = Tipo_de_tiposDAO::selectById( $id );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectCount( $where=null ){
		$result = Tipo_de_tiposDAO::selectCount( $where );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectAllPagination( $orderBy=null, $where=null, $page=null,  $rowsPerPage= null){
		$result = Tipo_de_tiposDAO::selectAllPagination( $orderBy, $where, $page,  $rowsPerPage );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectAll( $orderBy=null, $where=null ){
		$result = Tipo_de_tiposDAO::selectAll( $orderBy, $where );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function save( Tipo_de_tiposVO $objVo ){
		$result = null;
		if( $objVo->getIdtipo_de_tipos() ) {
			$result = Tipo_de_tiposDAO::update( $objVo );
		} else {
			$result = Tipo_de_tiposDAO::insert( $objVo );
		}
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function delete( $id ){
		$result = Tipo_de_tiposDAO::delete( $id );
		return $result;
	}

}
?>