<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-21 23:29:28
 */

if ( !function_exists( 'ap1v_autoload') ) {
	function ap1v_autoload( $class_name ){
		if (file_exists(__DIR__.DS.$class_name.'.class.php')){
			require_once $class_name.'.class.php';
		} else {
			return false;
		}
	}
spl_autoload_register('ap1v_autoload');
}