<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.9.0-alpha
 * FormDin Version: 4.7.5-alpha
 * 
 * System appev2 created in: 2019-09-01 16:03:50
 */
class Selmenuqtd
{


    private $dao = null;

    public function __construct()
    {
        $this->dao = new SelmenuqtdDAO();
    }
    public function getDao()
    {
        return $this->dao;
    }
    public function setDao($dao)
    {
        $this->dao = $dao;
    }
    //--------------------------------------------------------------------------------
    public function execProcedure( SelmenuqtdVO $objVo )
    {
        $result = $this->dao->execProcedure( $objVo );
        return $result;
    }

}
?>