<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.3.1-alpha
 * FormDin Version: 4.5.1-alpha
 * 
 * System xx created in: 2019-04-14 20:35:32
 */
class MarcaVO
{
    private $idmarca = null;
    private $nom_marca = null;
    private $idpessoa = null;
    public function __construct( $idmarca=null, $nom_marca=null, $idpessoa=null ) {
        $this->setIdmarca( $idmarca );
        $this->setNom_marca( $nom_marca );
        $this->setIdpessoa( $idpessoa );
    }
    //--------------------------------------------------------------------------------
    public function setIdmarca( $strNewValue = null )
    {
        $this->idmarca = $strNewValue;
    }
    public function getIdmarca()
    {
        return $this->idmarca;
    }
    //--------------------------------------------------------------------------------
    public function setNom_marca( $strNewValue = null )
    {
        $this->nom_marca = $strNewValue;
    }
    public function getNom_marca()
    {
        return $this->nom_marca;
    }
    //--------------------------------------------------------------------------------
    public function setIdpessoa( $strNewValue = null )
    {
        $this->idpessoa = $strNewValue;
    }
    public function getIdpessoa()
    {
        return $this->idpessoa;
    }
    //--------------------------------------------------------------------------------
}
?>