<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System appev2 created in: 2019-11-01 22:23:15
 */
class Meta_tipoVO
{
    private $idmetatipo = null;
    private $descricao = null;
    private $sit_ativo = null;
    public function __construct( $idmetatipo=null, $descricao=null, $sit_ativo=null ) {
        $this->setIdmetatipo( $idmetatipo );
        $this->setDescricao( $descricao );
        $this->setSit_ativo( $sit_ativo );
    }
    //--------------------------------------------------------------------------------
    public function setIdmetatipo( $strNewValue = null )
    {
        $this->idmetatipo = $strNewValue;
    }
    public function getIdmetatipo()
    {
        return $this->idmetatipo;
    }
    //--------------------------------------------------------------------------------
    public function setDescricao( $strNewValue = null )
    {
        $this->descricao = $strNewValue;
    }
    public function getDescricao()
    {
        return $this->descricao;
    }
    //--------------------------------------------------------------------------------
    public function setSit_ativo( $strNewValue = null )
    {
        $this->sit_ativo = $strNewValue;
    }
    public function getSit_ativo()
    {
        return $this->sit_ativo;
    }
    //--------------------------------------------------------------------------------
}
?>