<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.9.0-alpha
 * FormDin Version: 4.7.5-alpha
 * 
 * System appev2 created in: 2019-09-01 16:03:50
 */
class SelfilhosmenuDAO 
{

    private $tpdo = null;

    public function __construct() {
        $tpdo = New TPDOConnectionObj();
        $this->setTPDOConnection($tpdo);
    }
    public function getTPDOConnection()
    {
        return $this->tpdo;
    }
    public function setTPDOConnection($TPDOConnection)
    {
        $this->tpdo = $TPDOConnection;
    }
    public function execProcedure( SelfilhosmenuVO $objVo )
    {
        $parameters = null;

        $idmenu_pai = $objVo->getIdmenu_pai();
        $idmenu_pai = SqlHelper::attributeIsset($idmenu_pai,' idmenu_pai ='.$idmenu_pai,'');
        $parameters = $parameters.$idmenu_pai;
        $sql = 'CALL form_exemplo.selfilhosmenu('.$parameters.')';
        $result = $this->tpdo->executeSql($sql);
        return $result;
    }
}
?>