<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.10.1-alpha
 * FormDin Version: 4.7.9-alpha
 * 
 * System xx created in: 2019-11-01 22:11:31
 */
class Vw_regiao_municipioVO
{
    private $cod_regiao = null;
    private $nom_regiao = null;
    private $cod_uf = null;
    private $nom_uf = null;
    private $sig_uf = null;
    private $cod_municipio = null;
    private $nom_municipio = null;
    private $sit_ativo = null;
    public function __construct( $cod_regiao=null, $nom_regiao=null, $cod_uf=null, $nom_uf=null, $sig_uf=null, $cod_municipio=null, $nom_municipio=null, $sit_ativo=null ) {
        $this->setCod_regiao( $cod_regiao );
        $this->setNom_regiao( $nom_regiao );
        $this->setCod_uf( $cod_uf );
        $this->setNom_uf( $nom_uf );
        $this->setSig_uf( $sig_uf );
        $this->setCod_municipio( $cod_municipio );
        $this->setNom_municipio( $nom_municipio );
        $this->setSit_ativo( $sit_ativo );
    }
    //--------------------------------------------------------------------------------
    public function setCod_regiao( $strNewValue = null )
    {
        $this->cod_regiao = $strNewValue;
    }
    public function getCod_regiao()
    {
        return $this->cod_regiao;
    }
    //--------------------------------------------------------------------------------
    public function setNom_regiao( $strNewValue = null )
    {
        $this->nom_regiao = $strNewValue;
    }
    public function getNom_regiao()
    {
        return $this->nom_regiao;
    }
    //--------------------------------------------------------------------------------
    public function setCod_uf( $strNewValue = null )
    {
        $this->cod_uf = $strNewValue;
    }
    public function getCod_uf()
    {
        return $this->cod_uf;
    }
    //--------------------------------------------------------------------------------
    public function setNom_uf( $strNewValue = null )
    {
        $this->nom_uf = $strNewValue;
    }
    public function getNom_uf()
    {
        return $this->nom_uf;
    }
    //--------------------------------------------------------------------------------
    public function setSig_uf( $strNewValue = null )
    {
        $this->sig_uf = $strNewValue;
    }
    public function getSig_uf()
    {
        return $this->sig_uf;
    }
    //--------------------------------------------------------------------------------
    public function setCod_municipio( $strNewValue = null )
    {
        $this->cod_municipio = $strNewValue;
    }
    public function getCod_municipio()
    {
        return $this->cod_municipio;
    }
    //--------------------------------------------------------------------------------
    public function setNom_municipio( $strNewValue = null )
    {
        $this->nom_municipio = $strNewValue;
    }
    public function getNom_municipio()
    {
        return $this->nom_municipio;
    }
    //--------------------------------------------------------------------------------
    public function setSit_ativo( $strNewValue = null )
    {
        $this->sit_ativo = $strNewValue;
    }
    public function getSit_ativo()
    {
        return $this->sit_ativo;
    }
    //--------------------------------------------------------------------------------
}
?>