<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0-alpha
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-20 23:14:14
 */

define('SYSTEM_NAME'    , 'Sistema exemplo 2.5');
define('SYSTEM_ACRONYM' , 'APPEV25');
define('SYSTEM_VERSION' , '2.5.0');
define('APLICATIVO'     , SYSTEM_ACRONYM);
define('DS'   , DIRECTORY_SEPARATOR);
?>