<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 0.9.0
 * FormDin Version: 4.2.6-alpha
 * 
 * System ap2v created in: 2018-11-21 23:30:54
 */

class Autoridade {


	public function __construct(){
	}
	//--------------------------------------------------------------------------------
	public static function selectById( $id ){
		$result = AutoridadeDAO::selectById( $id );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectCount( $where=null ){
		$result = AutoridadeDAO::selectCount( $where );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectAllPagination( $orderBy=null, $where=null, $page=null,  $rowsPerPage= null){
		$result = AutoridadeDAO::selectAllPagination( $orderBy, $where, $page,  $rowsPerPage );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function selectAll( $orderBy=null, $where=null ){
		$result = AutoridadeDAO::selectAll( $orderBy, $where );
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function validar( AutoridadeVO $objVo) {
	    //Invertendo a string de data pois vem da tela dd-mm-yyyy
	    // e o mysql só entende yyyy-mm-dd
	    $dat_evento = implode("-", array_reverse(explode("/", $objVo->getDat_evento())));
	    
	    $ordem = $objVo->getOrdem();
	    $where = 'ordem ='.$ordem.' and dat_evento = \''.$dat_evento.'\'';
	    $resultado = AutoridadeDAO::selectAll(null, $where);
	    
	    if (is_array($resultado) && count($resultado)>0) {
	        $msg = "No evento do mesmo dia só pode ter uma autoridade da mesma ordem";
	        throw new DomainException($msg);
	    }
	}
	//--------------------------------------------------------------------------------
	public static function save( AutoridadeVO $objVo ){
		$result = null;
		self::validar($objVo);
		if( $objVo->getIdautoridade() ) {
			$result = AutoridadeDAO::update( $objVo );
		} else {
			$result = AutoridadeDAO::insert( $objVo );
		}
		return $result;
	}
	//--------------------------------------------------------------------------------
	public static function delete( $id ){
		$result = AutoridadeDAO::delete( $id );
		return $result;
	}
}
?>