<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.5.1-alpha
 * FormDin Version: 4.5.3-alpha
 * 
 * System appev2 created in: 2019-05-10 01:18:59
 */

if ( !function_exists( 'appev2_autoload') ) {
    function appev2_autoload( $class_name )
    {
        $path = __DIR__.DS.$class_name.'.class.php';
        if (file_exists($path)){
            require_once $path;
        } else {
            return false;
        }
    }
spl_autoload_register('appev2_autoload');
}